>>> PRAGMA table_info(GUIDE);
PRAGMA table_info(CUSTOMER);
PRAGMA table_info(RESERVATION);
PRAGMA table_info(TRIP);
PRAGMA table_info(TRIP_GUIDES);

>>> SELECT * FROM GUIDE;
SELECT * FROM CUSTOMER;
SELECT * FROM RESERVATION;
SELECT * FROM TRIP;
SELECT * FROM TRIP_GUIDES;
